global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "credit-scoring-api"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 10s
